### ISSUE TITLE
Issue Lazy Loading Pinterest

### ISSUE THREAD

**Issue by roelmagdaleno** [ressio/lazy-load-xt#103]
Hi, a few days ago I was able to lazy load Facebook, Twitter and Instagram, now I'm trying to lazy load some Pinterest's embeds, but just work with the **follow button**, it's not working with Pinterest boards, profiles, etc...

Does anyone have the same issue? What should I do?

Thanks.

**Comment by RoelMagdaleno** [comment]
Hi again! I already fixed this!

The issue was happening because Pinterest gives us this tag structure (without text inside of the tag):

`<a data-pin-do="buttonBookmark" data-pin-save="true" href="https://www.pinterest.com/pin/create/button/"></a>`

But, if you add some text inside of the tag, it works perfect:

`<a data-pin-do="buttonBookmark" data-pin-save="true" href="https://www.pinterest.com/pin/create/button/">Pinterest</a>`

If you're working with some backend script, you should add the text dynamically. Hope someone else found this comment useful. :)
