### ISSUE TITLE
Why does lazyloadxt bind to touchmove AND scroll event?

### ISSUE THREAD

**Issue by valnub** [ressio/lazy-load-xt#91]
I noticed that lazyloadxt calls `queueCheckLazyElements()` whenever at least one of these events is called:

`load orientationchange resize scroll touchmove focus`

This means that on mobile devices `queueCheckLazyElements()` always gets called twice when the user scrolls the whole page. This is a pretty nasty performance issue on older devices. I especially noticed this on an iPhone5 with iOS9 on Safari Browser.

Would it be possible to remove touchmove from this list or provide a smarter solution?

**Comment by CheemaSingh** [comment]
You can choose the events as per your requirement, then bind them for lazy load as:
```
$.extend($.lazyLoadXT, {                
                updateEvent: 'click load orientationchange resize scroll '
            });
```
**But you should not remove touchmove event, because if you have a touch slider on the webpage and you change the slide swiping right or left then it won't trigger the lazy load for the new slide unless user scroll down or click somewhere on the webpage!**

**Comment by valnub** [comment]
@CheemaSingh Oh, thanks for the hint. That's very handy. However, I use my slider's `onSlideEnd` event to call `$(window).trigger('scroll')` after a slide transition has ended to trigger lazy load to get new images. I think that's way more efficient than applying `touchmove` on the whole page.
